const MMSuggestions = {
    "Deku Stick": ("(Glitch) You can use the Infinite Sword glitch to kill things",
    ""),
    "Fairy Slingshot": ("There is a skulltula in the Deku Tree on the lower floor to grab.",
    ""),
    "Deku Nuts": (""),
    "Ocarina" :(""),
    "Bomb Bag": (""),
    "Boomerang": (""),
    "Hookshot": (""),
    "Longshot": (""),
    "Bow": (""),
    "Beans": (""),
    "Fire Arrows": (""),
    "Ice Arrows": (""),
    "Light Arrows": (""),
    "Din's Fire": (""),
    "Farore's Wind": (""),
    "Nayru's Love": (""),
    "Megaton Hammer": (""),
    "Lens of Truth": (""),
    "Trade Items": (""),
    "Bottle": ("")
}